# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pruangde <pruangde@student.42bangkok.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/17 00:37:39 by pruangde          #+#    #+#              #
#    Updated: 2023/07/01 15:35:11 by pruangde         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= megaphone

CC 			= c++
CFLAGS		= -Wall -Wextra -Werror -std=c++98
CPPFLAGS	= -std=c++98

FILE = megaphone.cpp

all:
	$(CC) $(CFLAGS) $(CPPFLAGS) $(FILE) -o $(NAME)